---
title: "eds_212_day4_comp2"
format: html
editor: visual
execute: 
  warning: FALSE
---

## my change

```{r}
library(GGally)
library(skimr)
library(palmerpenguins)
library(tidyverse)
```

Basic data exploration

-   names: get variable names

-   dim: data dimensions

-   head: get first n lines (6 by default)

-   tail: get last n lines (6 by default)

-   summary: get basic summary statistic

```{r}
names(penguins)

dim(penguins)

head(penguins)

tail(penguins)

summary(penguins)
```

```{r}
# data exploration tool
skim(penguins)
```

```{r}
ggpairs(penguins)
```

```{r}
penguins %>%
  select(species, body_mass_g, ends_with("_mm")) %>% 
  GGally::ggpairs(aes(color = species)) +
  scale_colour_manual(values = c("darkorange","purple","cyan4")) +
  scale_fill_manual(values = c("darkorange","purple","cyan4"))
```

making more exploratory charts in ggplot2

histogram

```{r}
ggplot(data = penguins, aes(x = flipper_length_mm)) +
  geom_histogram(fill = "purple",
                 color = "orange") +
  theme_minimal()
```

box plot

```{r}
ggplot(data = penguins,
       aes(x = species,
           y = bill_length_mm)) +
  geom_boxplot(fill = "blue", 
               color = "orange") +
  geom_jitter(aes(size = bill_depth_mm, color = bill_depth_mm), 
              alpha = 0.5) + 
  theme_dark()
```
